# Generated by Django 6.0.6 on 2026-07-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User settings', 'verbose_name_plural': 'User settings'},
        ),
    ]
